---
apiVersion: v1
kind: Namespace
metadata:
  name: theol

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke
  namespace: theol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quelpoke
  template:
    metadata:
      labels:
        app: quelpoke
    spec:
      containers:
      - name: quelpoke
        image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-theol/quelpoke:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quelpoke
  namespace: theol
spec:
  selector:
    app: quelpoke
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: quelpoke-route
  namespace: theol
spec:
  parentRefs:
  - kind: Gateway
    name: external-http-gateway     # ✅ TA PAS BESOIN DE LE CRÉER
    namespace: infra                # ✅ DOIT EXISTER DEJA
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /theol             # ✅ URL finale = http(s)://IP_GATEWAY/thomasg
    backendRefs:
    - name: quelpoke
      port: 8080